  // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWZ4Zw8hb1WzKIpq_U0wncZzhPiz6lP_Y',
    appId: '1:323015214184:web:1f34ebfb89e0f9b07aa7dd',
    messagingSenderId: '323015214184',
    projectId: 'studyapp-a98c0',
    authDomain: 'studyapp-a98c0.firebaseapp.com',
    storageBucket: 'studyapp-a98c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe2Lb8xpQ4EtLENjAHfNOU7lhXs_SYB_w',
    appId: '1:323015214184:android:32dbac3d7935a14a7aa7dd',
    messagingSenderId: '323015214184',
    projectId: 'studyapp-a98c0',
    storageBucket: 'studyapp-a98c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8pKWfCT_GEoJVFfDriAfxLPqTnbro_xc',
    appId: '1:323015214184:ios:561f7abb8af6cda87aa7dd',
    messagingSenderId: '323015214184',
    projectId: 'studyapp-a98c0',
    storageBucket: 'studyapp-a98c0.appspot.com',
    iosClientId: '323015214184-bgecd38ep43dqo07ukpl799olgb0dvee.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyapp',
  );
}
